const ManagerSalesSummary = () => {
    return (
        <div>
            <p>
            9. Sales Summary <br />
On This Route The Shop-manager can show all the sales generated by the Shop Employees,<br />
Sales Chart
Sales Count
This Section will show 3 cards. Where There Will be following information <br />
● Total Sale <br />
● Total Invest <br />
● Total Profit <br />
Sales History <br />
Show a Table of Sold Products. Show Sales collection by sorting them according to sales
date in a descending order. The Sales card will have following information <br />
● Product Name <br />
● Selling date <br />
● Profit ( productionCost - totalSell) <br />
Apply Pagination on the Sale History component. <br />
            </p>

        </div>
    );
};

export default ManagerSalesSummary;